<?php
/** @var $block \Ainnomix\EtmAdminUi\Block\Adminhtml\EntityAttribute\Edit\Tab\Labels  */
?>

<div class="fieldset-wrapper admin__collapsible-block-wrapper opened" id="manage-titles-wrapper">
    <div class="fieldset-wrapper-title">
        <strong class="admin__collapsible-title" data-toggle="collapse" data-target="#manage-titles-content">
            <span><?= /* @noEscape */ __('Manage Titles (Size, Color, etc.)') ?></span>
        </strong>
    </div>
    <div class="fieldset-wrapper-content in collapse" id="manage-titles-content">
        <fieldset class="admin__fieldset fieldset">
            <div class="admin__control-table-wrapper">
                <table class="admin__control-table" id="attribute-labels-table">
                    <thead>
                    <tr>
                        <?php foreach ($block->getStores() as $store): ?>
                            <th class="col-store-view"><?= /* @escapeNotVerified */ $store->getName() ?></th>
                        <?php endforeach; ?>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <?php $labels = $block->getLabelValues() ?>
                        <?php foreach ($block->getStores() as $store): ?>
                            <td class="col-store-view">
                                <input class="input-text<?php if ($store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID): ?> required-option<?php endif; ?>" type="text" name="frontend_label[<?= /* @escapeNotVerified */ $store->getId() ?>]" value="<?= $block->escapeHtml($labels[$store->getId()]) ?>"<?php if ($block->getReadOnly()):?> disabled="disabled"<?php endif;?>/>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                    </tbody>
                </table>
            </div>
        </fieldset>
    </div>
</div>
