name: Code Quality

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  static-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup source code
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools:
            - composer:v1
            - phpcs:3.4

      - name: Run phpcs
        run: .tools/phpcs
