name: Code Quality

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  static-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup source code
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer:v1, phpcs:3.4

      - name: Install Magento composer repository auth
        run: ./tools/composer config -a http-basic.repo.magento.com $COMPOSER_MAGENTO_PUB_KEY $COMPOSER_MAGENTO_PRIV_KEY
        env:
          COMPOSER_MAGENTO_PUB_KEY: ${{ secrets.COMPOSER_MAGENTO_PUB_KEY }}
          COMPOSER_MAGENTO_PRIV_KEY: ${{ secrets.COMPOSER_MAGENTO_PRIV_KEY }}

      - name: Add Magento composer repository
        run: ./tools/composer repositories.magento composer https://repo.magento.com/

      - name: Install composer dependencies
        run: ./tools/composer install --no-interaction --no-ansi

      - name: Run phpcs
        run: ./tools/phpcs
